/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.apache.commons.lang3.StringUtils;

public class Main {
    public static void main(String[] args) {
        System.out.println(StringUtils.capitalize("hello master"));
        System.out.println(StringUtils.capitalize("hello gradle"));
	System.out.println(StringUtils.upperCase("Hello Gradle"));
	System.out.println(StringUtils.upperCase("Hello new feature Gradle"));
    }
}
